import { useEffect, useState } from 'react';
import { Loader2, QrCode, Save } from 'lucide-react';
import { api } from '../auth/useAuth';
import { useAlert } from '../contexts/AlertContext';

export default function NotificacoesDTF() {
  const { addAlert } = useAlert(); const [config, setConfig] = useState<any>({ ativo: false, service_url: '', service_token: '' }); const [connection, setConnection] = useState<any>(null); const [loading, setLoading] = useState(false);
  const load = async () => { const r = await api.get('dtf-notificacoes-config/'); setConfig(r.data); try { setConnection((await api.get('dtf-notificacoes-config/connection/')).data); } catch { setConnection({ status: 'indisponivel' }); } };
  useEffect(() => { load(); }, []);
  const save = async () => { setLoading(true); try { await api.patch(`dtf-notificacoes-config/${config.id}/`, config); addAlert('Configuração salva.', 'success'); await load(); } catch { addAlert('Não foi possível salvar.', 'error'); } finally { setLoading(false); } };
  const reconnect = async () => { setLoading(true); try { await api.post('dtf-notificacoes-config/reconnect/'); await load(); } catch { addAlert('Serviço indisponível.', 'error'); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-4xl p-6 md:p-10"><p className="text-xs font-black uppercase tracking-widest text-blue-600">DTF</p><h1 className="mt-2 text-3xl font-black text-slate-900">Notificações WhatsApp</h1><p className="mt-2 text-slate-500">Instância exclusiva para avisos automáticos. Não é a central de atendimento.</p><div className="mt-8 grid gap-6 md:grid-cols-2"><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-black">Conexão</h2><p className="mt-3 text-sm">Status: <b>{connection?.status || 'carregando'}</b></p>{connection?.number && <p className="mt-1 text-sm text-slate-500">Número: {connection.number}</p>}{connection?.qr && <img src={connection.qr} className="mx-auto mt-5 w-56 rounded-xl" alt="QR Code do WhatsApp"/>}<button onClick={reconnect} disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-900 py-3 text-sm font-bold text-white"><QrCode size={16}/> Gerar/atualizar QR</button></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-black">Serviço</h2><label className="mt-4 block text-xs font-bold text-slate-500">URL interna</label><input value={config.service_url || ''} onChange={e => setConfig({...config, service_url:e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm"/><label className="mt-4 block text-xs font-bold text-slate-500">Token interno</label><input type="password" value={config.service_token || ''} onChange={e => setConfig({...config, service_token:e.target.value})} className="mt-1 w-full rounded-xl border p-3 text-sm" placeholder="Defina o mesmo token do serviço"/><label className="mt-5 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={!!config.ativo} onChange={e => setConfig({...config, ativo:e.target.checked})}/> Ativar disparos automáticos</label><button onClick={save} disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-bold text-white">{loading?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>} Salvar configuração</button></section></div></div>;
}
