# Generated by Django 6.0.1 on 2026-02-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('financeiro', 'Financeiro')], default='vendedor', max_length=20),
        ),
    ]
