# Generated by Django 6.0.1 on 2026-05-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='cor',
            field=models.CharField(default='#25D366', help_text='Cor em hexadecimal para o chat!', max_length=7),
        ),
    ]
