# Generated by Django 6.0.1 on 2026-05-01 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('from_me', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('contato_nome', models.CharField(blank=True, max_length=100)),
                ('lida', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='api.whatsappinstance')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instance', 'from_number'], name='api_whatsap_instanc_da637d_idx'), models.Index(fields=['timestamp'], name='api_whatsap_timesta_a59be7_idx')],
            },
        ),
    ]
