# Generated by Django 6.0.1 on 2026-05-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_whatsappinstance_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='jid',
            field=models.CharField(blank=True, max_length=53, null=True, unique=True),
        ),
    ]
