# Generated by Django 6.0.1 on 2026-02-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemorcamento_descricao_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='produto_nome_no_ato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produto'),
        ),
    ]
