# Generated by Django 6.0.1 on 2026-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='cor',
            field=models.CharField(default='#25D366', help_text='Cor da instância (hex, ex: #25D366)', max_length=7),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_type',
            field=models.CharField(blank=True, help_text='Tipo de mídia (image, video, document, etc)', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL da mídia (imagem, vídeo, etc)'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='reply_to_message_id',
            field=models.CharField(blank=True, help_text='ID da mensagem que esta responde (reply)', max_length=255),
        ),
    ]
