# Generated by Django 6.0.1 on 2026-02-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itemorcamento_produto_nome_no_ato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='template_id',
            field=models.IntegerField(choices=[(1, 'Empresa 1'), (2, 'Empresa 2'), (3, 'Empresa 3')], default=1),
        ),
    ]
