# Generated by Django 6.0.1 on 2026-05-05 02:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cliente_jid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTFConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_produto', models.CharField(choices=[('dtf_textil', 'DTF Têxtil'), ('dtf_uv', 'DTF UV'), ('sublimacao', 'Sublimação')], max_length=20, unique=True)),
                ('valor_metro', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=10)),
                ('preco_minimo', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuração DTF',
                'verbose_name_plural': 'Configurações DTF',
            },
        ),
        migrations.AddField(
            model_name='dtfvendor',
            name='tipo_produto',
            field=models.CharField(choices=[('dtf_textil', 'DTF Têxtil'), ('dtf_uv', 'DTF UV'), ('sublimacao', 'Sublimação')], default='dtf_textil', max_length=20),
        ),
        migrations.AddField(
            model_name='dtfvendor',
            name='unidade',
            field=models.CharField(choices=[('ml', 'Metro Linear'), ('m2', 'Metro Quadrado')], default='ml', max_length=2),
        ),
    ]
