# Generated by Django 6.0.1 on 2026-05-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_cor_and_reply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='jid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
