# Generated by Django 6.0.1 on 2026-05-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_jid_to_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='jid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
