# Generated by Django 6.0.1 on 2026-02-07 15:38

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empresa_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='dtfvendor',
            name='comprovante_pagamento',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path_comprovante_dtf),
        ),
        migrations.AlterField(
            model_name='dtfvendor',
            name='layout_arquivo',
            field=models.FileField(upload_to=api.models.path_layout_dtf),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('financeiro', 'Financeiro'), ('maquina', 'Máquina')], default='vendedor', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_descricao', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=100)),
                ('aplicacao_arte', models.CharField(max_length=100)),
                ('detalhes_tamanho', models.JSONField(default=dict, help_text='Grade de tamanhos ou quantidade única')),
                ('layout', models.FileField(upload_to=api.models.path_layout)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado')], default='pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
    ]
