# Generated by Django 6.0.1 on 2026-05-04 05:18

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_empresa_template_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('conectando', 'Conectando'), ('desconectado', 'Desconectado')], default='inativo', max_length=20)),
                ('cor', models.CharField(default='#25D366', help_text='Cor em hexadecimal para o chat', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profile_pic_url', models.URLField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('connection_status', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='jid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='agencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='campanha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_print',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='dtfvendor',
            name='comprovante_pagamento',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path_comprovante_dtf),
        ),
        migrations.AlterField(
            model_name='dtfvendor',
            name='layout_arquivo',
            field=models.FileField(upload_to=api.models.path_layout_dtf),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('financeiro', 'Financeiro'), ('maquina', 'Máquina')], default='vendedor', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_descricao', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=100)),
                ('aplicacao_arte', models.CharField(max_length=100)),
                ('detalhes_tamanho', models.JSONField(default=dict, help_text='Grade de tamanhos ou quantidade única')),
                ('layout', models.FileField(upload_to=api.models.path_layout)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado')], default='pendente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('from_me', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('contato_nome', models.CharField(blank=True, default='', max_length=100)),
                ('lida', models.BooleanField(default=False)),
                ('msg_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('sticker', 'Sticker'), ('contact', 'Contato'), ('location', 'Localização')], default='text', max_length=20)),
                ('media_url', models.TextField(blank=True, default='')),
                ('reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='api.whatsappinstance')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['instance', 'from_number'], name='api_whatsap_instanc_da637d_idx'), models.Index(fields=['timestamp'], name='api_whatsap_timesta_a59be7_idx')],
            },
        ),
    ]
