# Generated by Django 6.0.1 on 2026-05-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dtfconfig_dtfvendor_tipo_produto_dtfvendor_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
