# Generated by Django 6.0.1 on 2026-02-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='agencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='campanha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_print',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
