# Generated by Django 6.0.1 on 2026-06-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_numero_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfvendor',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aprovado', 'Aprovado'), ('em_producao', 'Em Produção'), ('finalizado', 'Finalizado')], default='orcamento', max_length=20),
        ),
    ]
