# Generated by Django 6.0.1 on 2026-06-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dtfvendor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_chave_telefone', models.CharField(blank=True, help_text='Chave PIX tipo telefone (formato: +5585999999999)', max_length=20, null=True)),
                ('pix_beneficiario', models.CharField(default='Loja', help_text='Nome do favorecido (máx 25 chars, sem acentos)', max_length=25)),
                ('pix_cidade', models.CharField(default='Sao Paulo', help_text='Cidade do beneficiário (máx 15 chars, sem acentos)', max_length=15)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
