# Generated by Django 6.0.1 on 2026-06-27 01:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_configuracaoloja'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfconfig',
            name='valor_unidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text="Valor por unidade (usado apenas para tipo_produto='estampa')", max_digits=10),
        ),
        migrations.AddField(
            model_name='dtfvendor',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=1, help_text="Quantidade de unidades (somente para tipo_produto='estampa')", null=True),
        ),
        migrations.AlterField(
            model_name='dtfconfig',
            name='tipo_produto',
            field=models.CharField(choices=[('dtf_textil', 'DTF Têxtil'), ('dtf_uv', 'DTF UV'), ('sublimacao', 'Sublimação'), ('estampa', 'Estampa (por unidade)')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dtfvendor',
            name='tipo_produto',
            field=models.CharField(choices=[('dtf_textil', 'DTF Têxtil'), ('dtf_uv', 'DTF UV'), ('sublimacao', 'Sublimação'), ('estampa', 'Estampa (por unidade)')], default='dtf_textil', max_length=20),
        ),
        migrations.AlterField(
            model_name='dtfvendor',
            name='unidade',
            field=models.CharField(choices=[('ml', 'Metro Linear'), ('m2', 'Metro Quadrado'), ('un', 'Unidade')], default='ml', max_length=2),
        ),
    ]
