# Generated by Django 6.0.1 on 2026-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dtfconfig_valor_unidade_dtfvendor_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfvendor',
            name='preco_unit_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Se preenchido, sobrescreve DTFConfig.valor_unidade (somente para tipo_produto='estampa')", max_digits=10, null=True),
        ),
    ]
