# Generated by Django 6.0.1 on 2026-06-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dtfvendor_preco_unit_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtfvendor',
            name='preco_unit_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sobrescreve o preço base do pedido (unidade para estampa, m² para sublimação, metro linear para DTF têxtil/UV). Nulo = usa config padrão.', max_digits=10, null=True),
        ),
    ]
