# Generated by Django 6.0.1 on 2026-07-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_mp_oauth_codigo_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtfvendor',
            name='comprovante_mp_data',
            field=models.JSONField(blank=True, help_text='Dados do pagamento via Mercado Pago (recebedor, método,最后的4 dígitos, etc.)', null=True),
        ),
    ]
