# Generated by Django 6.0.1 on 2026-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mp_comprovante_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoloja',
            name='mp_public_key',
            field=models.TextField(blank=True, default='', help_text='Public Key do Mercado Pago (para Checkout Transparente)'),
        ),
    ]
